### ISSUE TITLE
React used by app conflicts with library

### ISSUE THREAD

**Issue by DomKM** [jmmk/javascript-externs-generator#3]
Attempting to create externs for [`react-relay`](http://cdn.jsdelivr.net/webjars/org.webjars.npm/react-relay/0.7.3/dist/relay.js) due to two reasons:

1. Relay expects `ReactDOM` to be defined, not `React.DOM`. As a user, this is easy to fix. Just open console and type `ReactDOM = React.DOM`.
2. Relay fails with `Super expression must either be null or a function, not undefined`. From researching this, it appears to be due to this app's old version of React (0.12.2) being incompatible with this version of Relay.

As a short-term solution, I'd suggest that React be upgraded to the most recent version to fix this conflict and likely many others, since so many libraries rely on React.
As a long-term solution, I'd consider if the UI could be rewritten using just the Google Closure Library without any external dependencies.

**Comment by jmmk** [comment]
I added an iframe to contain the loaded scripts so that they won't interact with libraries used in the app.

To generate an extern for react-relay, I took the following steps:

- load [React](https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xtp1/t39.3284-6/12624079_897774290317920_1379776191_n.js)
- load [ReactDOM](https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xfp1/t39.3284-6/12624052_751451571621845_431133942_n.js)
- load [Relay](http://cdn.jsdelivr.net/webjars/org.webjars.npm/react-relay/0.7.3/dist/relay.js)
- Generate Extern

**Comment by jmmk** [comment]
Just realized I forgot to deploy earlier, but the new changes are now up at http://jmmk.github.io/javascript-externs-generator/
