### ISSUE TITLE
MIME type ('text/plain') is not executable

### ISSUE THREAD

**Issue by Bost** [jmmk/javascript-externs-generator#35]
Hi, I'm trying to load https://gitgud.io/unconed/mathbox/raw/0.0.5/build/mathbox-bundle.js on the http://jmmk.github.io/javascript-externs-generator/ and I get:
```
Refused to execute script from 'https://gitgud.io/unconed/mathbox/raw/0.0.5/build/mathbox-bundle.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```
What am I doing wrong?

**Comment by jmmk** [comment]
@Bost "raw" files on GitHub/GitLab/Gitgud are served as plain text rather than Javascript (see [here](https://raw.githack.com/#why) for a better explanation).

There are services like https://rawgit.com/ and https://raw.githack.com/ that work around this by serving content with the proper type, but they don't work with `gitgud.io` URLs like yours.

1. You can clone that repo to GitHub/BitBucket/GitLab and use one of the above services to get it to load properly in the webapp
2. You can download `mathbox-bundle.js` and use the command line tool instead (see README for instructions)

**Comment by Bost** [comment]
Thanx @jmmk
