### ISSUE TITLE
Won't load echarts.js 

### ISSUE THREAD

**Issue by clov0** [jmmk/javascript-externs-generator#37]
Load fails (nothing is printed) on either echarts' js files : 
https://ecomfe.github.io/echarts-doc/public/en/download.html

**Comment by jmmk** [comment]
@clov0 If you try to use a URL like `https://raw.githubusercontent.com/ecomfe/echarts/3.8.5/dist/echarts.js`, it won't work properly due to the content type (plain text instead of JS). You can use a service like https://rawgit.com/ and load the URL `https://rawgit.com/ecomfe/echarts/3.8.5/dist/echarts.js` instead that should work

So in order to generate the extern:

- Go to https://jmmk.github.io/javascript-externs-generator/
- Load `https://rawgit.com/ecomfe/echarts/3.8.5/dist/echarts.js`
- Type in `echarts`
- Click `Extern!`
